---task 01
USE UNIVER;
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	from AUDITORIUM Inner Join AUDITORIUM_TYPE
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

---task 02
USE UNIVER;
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	from AUDITORIUM Inner Join AUDITORIUM_TYPE
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE 
		and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME Like '%компьютер%'


---task 03
USE UNIVER;
SELECT	STUDENT.[NAME],
		FACULTY.FACULTY_NAME, 
		PULPIT.PULPIT_NAME,
		GROUPS.PROFESSION,
	    [SUBJECT].SUBJECT_NAME,
		PROGRESS.NOTE,
		CASE 
            WHEN PROGRESS.NOTE = 6 THEN N'шесть'
            WHEN PROGRESS.NOTE = 7 THEN N'семь'
            WHEN PROGRESS.NOTE = 8 THEN N'восемь'
			ELSE N'неизвестно'
        END MARK
	from STUDENT 
	inner join GROUPS
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	inner join PROGRESS
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
	inner join [SUBJECT]
	on [SUBJECT].[SUBJECT] = PROGRESS.[SUBJECT]
	inner join PULPIT
	on PULPIT.PULPIT = [SUBJECT].PULPIT
	inner join FACULTY
	on FACULTY.FACULTY = PULPIT.FACULTY
	where PROGRESS.NOTE between 6 and 8
	order by PROGRESS.NOTE
	
---task 04
USE UNIVER;
SELECT isnull( N'***',TEACHER.TEACHER_NAME) TEACHER_NAME,
		PULPIT.PULPIT_NAME
	from PULPIT left outer join TEACHER
	on TEACHER.PULPIT = PULPIT.PULPIT

---task 05
USE UNIVER;
SELECT STUDENT.NAME, PROGRESS.NOTE 
	from STUDENT FULL OUTER JOIN PROGRESS
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	--where PROGRESS.NOTE is not null

SELECT PROGRESS.NOTE, STUDENT.NAME 
	from PROGRESS FULL OUTER JOIN STUDENT
	on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where PROGRESS.NOTE is not null

SELECT PROGRESS.NOTE, STUDENT.NAME 
	from PROGRESS FULL OUTER JOIN STUDENT
	on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where PROGRESS.NOTE is null

---task 06
USE UNIVER;
SELECT AUDITORIUM.AUDITORIUM,
		AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	from AUDITORIUM cross join AUDITORIUM_TYPE
		--where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
		
